module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    promicro_pretty: require('./promicro_pretty'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),

    m2: require('./m2'),
    b3u1000p: require('./b3u1000p'),
    mountinghole: require('./mountinghole'),
    bat: require('./bat'),
    pcm12: require('./pcm12'),
}
